sudo: required
language: ruby
services:
- docker

before_install:
  - "./start_containers.sh"

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rake spec

after_success:
  - "./build_images.sh"
  - "./publish_images.sh"
