sudo: required
language: ruby
rvm:
  - 2.3.1

services:
- docker

before_install:
  - "./start_containers.sh"

script:
  - POSTGRES_PORT=8888 RAILS_ENV=test bundle exec rake db:create db:migrate
  - POSTGRES_PORT=8888 RAILS_ENV=test bundle exec rake spec

after_success:
  - "./build_images.sh"
  - "./publish_images.sh"
