global_sections:
  - transactions
  - transformations
  - settings

settings:
  default_section: general
  sections:
    - general
    - tradeshift
    - rules
  
registry:
  url: http://xa-registry.herokuapp.com
